### ISSUE TITLE
Make file names more readable

### ISSUE THREAD

**Issue by misslivirose** [Mozilla-Ocho/Memory-Cache#10]
Use the title of the page when available to make the file names more easily readable.

**Comment by avelynhc** [comment]
I can work on adding a code formatter, [prettier](https://prettier.io/) in your repo.

**Comment by bharattech** [comment]
Hi, This is Bharat,
I'm interested in contributing to the project. 
I've reviewed the details of the this issue, and I believe I can help in resolving it.
Additionally, I would appreciate any feedback on my proposed solution, if you have any preferences.

Looking forward to your guidance. Thank you for your time and consideration!

Best regards,

**Comment by misslivirose** [comment]
Fixed in #43 - thank you @bharattech!

**Comment by bharattech** [comment]
🎉 Thank you for merging my pull request! 🚀 @misslivirose 

I'm thrilled to see this change integrated into the project. It was a great learning experience for me, and I'm grateful for the opportunity to contribute.

I'm looking forward to continuing to contribute to the project and collaborating with the community. Please let me know if there are specific areas or features where I can be of assistance.

Thanks again, and I'm excited to be part of this project!

Best regards,
Bharat
