### ISSUE TITLE
Extension issue -- Save As PDF functionality is printing to connecting printer by default

### ISSUE THREAD

**Issue by katetaylormoz** [Mozilla-Ocho/Memory-Cache#55]
**Issue:** Save As PDF functionality is printing to connecting printer by default
**Expected behaviour:** PDF is saved to defined MemoryCache folder in Downloads Directory

<img width="1375" alt="Screenshot 2024-02-12 at 4 37 39 PM" src="https://github.com/Mozilla-Ocho/Memory-Cache/assets/100849201/a7eb8d37-f232-4504-b820-a4ffcba21cca">

Utilizing source-build of Firefox with [these alterations](https://github.com/Mozilla-Ocho/Memory-Cache/wiki/Modifying-Firefox-to-Save-PDF-files-automagically-to-MemoryCache)
<img width="730" alt="Screenshot 2024-02-12 at 4 39 04 PM" src="https://github.com/Mozilla-Ocho/Memory-Cache/assets/100849201/db0ba12c-4d91-4efd-a26b-fd8c371caba6">

**Comment by katetaylormoz** [comment]
@bharattech is this something you might be interested in looking into?

**Comment by bharattech** [comment]
Hi @katetaylormoz ,

Yes sure, request you asign it me.

**Comment by bharattech** [comment]
Hi @katetaylormoz ,

Please confirm that you have rebuilt the Firefox source code after completing your coding changes from https://github.com/Mozilla-Ocho/Memory-Cache/wiki/Modifying-Firefox-to-Save-PDF-files-automagically-to-MemoryCache

Rebuild is the last step: 4.Rebuild an incremental build.

**Comment by katetaylormoz** [comment]
Confirmed. I have rebuilt Firefox after editing the code. Closing the ticket as the Printer dialog is not appearing anymore

**Comment by katetaylormoz** [comment]
Thank YOU for the help!
